version: "3.9"

services:
  generate:
    image: ${IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}_generate
    volumes:
      - .:/mnt/workspace
    working_dir: /mnt/workspace
    entrypoint: ["openc3", "cli", "generate", "target", "${TARGET_NAME}", "--python"]
    networks:
      - openc3-cosmos-network
    stdin_open: true
    tty: true

networks:
  openc3-cosmos-network:
    external: true
